INSERT INTO EMPLOYEE (id, DEPARTMENT, EMPLOYEE_NAME, EMPLOYEE_SALARY) VALUES (1, 'HR', 'Employee 1', 100000);
INSERT INTO EMPLOYEE (id, DEPARTMENT, EMPLOYEE_NAME, EMPLOYEE_SALARY) VALUES (2, 'HR', 'Employee 2', 150000);
INSERT INTO EMPLOYEE (id, DEPARTMENT, EMPLOYEE_NAME, EMPLOYEE_SALARY) VALUES (3, 'IoT', 'Employee 3', 300000);
INSERT INTO EMPLOYEE (id, DEPARTMENT, EMPLOYEE_NAME, EMPLOYEE_SALARY) VALUES (4, 'Sales', 'Employee 4', 200000);
INSERT INTO EMPLOYEE (id, DEPARTMENT, EMPLOYEE_NAME, EMPLOYEE_SALARY) VALUES (5, 'Sales', 'Employee 5', 250000);